### ISSUE TITLE
Use OCLP to Fix WiFi

### ISSUE THREAD

**Issue by DesignWhore** [Hgd-spec/Beelink-SER5PRO-5600H#1]
You Must Use OpenCore Legacy Patcher (OCLP) to fix Wifi / Kexts for Wifi in Sonoma.
Lookup the OpenCore Legacy patcher and info pages. there are many tutorials out there on youtube as well.
Cheers.
DesignWhore

**Comment by Hgd-spec** [comment]
Thanks, I'll give it a try.
